/** Auto-derived ISO 3166-1 names → alpha-2 (country-flag-icons supported). */
export const COUNTRY_NAME_TO_CODE = {
  "afghanistan": "AF",
  "åland islands": "AX",
  "albania": "AL",
  "algeria": "DZ",
  "american samoa": "AS",
  "andorra": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "aruba": "AW",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "bhutan": "BT",
  "bolivia, plurinational state of": "BO",
  "bonaire, sint eustatius and saba": "BQ",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "bouvet island": "BV",
  "brazil": "BR",
  "british indian ocean territory": "IO",
  "brunei darussalam": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cabo verde": "CV",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "cayman islands": "KY",
  "central african republic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "christmas island": "CX",
  "cocos (keeling) islands": "CC",
  "colombia": "CO",
  "comoros": "KM",
  "congo": "CG",
  "congo, democratic republic of the": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  "côte d'ivoire": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "curaçao": "CW",
  "cyprus": "CY",
  "czechia": "CZ",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "eswatini": "SZ",
  "ethiopia": "ET",
  "falkland islands (malvinas)": "FK",
  "faroe islands": "FO",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guernsey": "GG",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "heard island and mcdonald islands": "HM",
  "holy see": "VA",
  "honduras": "HN",
  "hong kong": "HK",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran, islamic republic of": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "isle of man": "IM",
  "israel": "IL",
  "italy": "IT",
  "jamaica": "JM",
  "japan": "JP",
  "jersey": "JE",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "korea, democratic people's republic of": "KP",
  "korea, republic of": "KR",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "lao people's democratic republic": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macao": "MO",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshall islands": "MH",
  "martinique": "MQ",
  "mauritania": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mexico": "MX",
  "micronesia, federated states of": "FM",
  "moldova, republic of": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands, kingdom of the": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norfolk island": "NF",
  "north macedonia": "MK",
  "northern mariana islands": "MP",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine, state of": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "pitcairn": "PN",
  "poland": "PL",
  "portugal": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "réunion": "RE",
  "romania": "RO",
  "russian federation": "RU",
  "rwanda": "RW",
  "saint barthélemy": "BL",
  "saint helena, ascension and tristan da cunha": "SH",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint martin (french part)": "MF",
  "saint pierre and miquelon": "PM",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "sint maarten (dutch part)": "SX",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south georgia and the south sandwich islands": "GS",
  "south sudan": "SS",
  "spain": "ES",
  "sri lanka": "LK",
  "sudan": "SD",
  "suriname": "SR",
  "svalbard and jan mayen": "SJ",
  "sweden": "SE",
  "switzerland": "CH",
  "syrian arab republic": "SY",
  "taiwan, province of china": "TW",
  "tajikistan": "TJ",
  "tanzania, united republic of": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tokelau": "TK",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "türkiye": "TR",
  "turkmenistan": "TM",
  "turks and caicos islands": "TC",
  "tuvalu": "TV",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom of great britain and northern ireland": "GB",
  "united states of america": "US",
  "united states minor outlying islands": "UM",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "venezuela, bolivarian republic of": "VE",
  "viet nam": "VN",
  "virgin islands (british)": "VG",
  "virgin islands (u.s.)": "VI",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
  "usa": "US",
  "uk": "GB",
  "burma": "MM",
  "south korea": "KR",
  "north korea": "KP",
  "czech republic": "CZ",
  "russia": "RU"
};
export const COUNTRY_NAME_KEYS_LONGEST_FIRST = ["united kingdom of great britain and northern ireland","saint helena, ascension and tristan da cunha","south georgia and the south sandwich islands","korea, democratic people's republic of","united states minor outlying islands","congo, democratic republic of the","heard island and mcdonald islands","venezuela, bolivarian republic of","bonaire, sint eustatius and saba","lao people's democratic republic","saint vincent and the grenadines","bolivia, plurinational state of","micronesia, federated states of","british indian ocean territory","tanzania, united republic of","falkland islands (malvinas)","french southern territories","netherlands, kingdom of the","saint martin (french part)","iran, islamic republic of","saint pierre and miquelon","sint maarten (dutch part)","taiwan, province of china","central african republic","northern mariana islands","turks and caicos islands","united states of america","virgin islands (british)","cocos (keeling) islands","bosnia and herzegovina","svalbard and jan mayen","saint kitts and nevis","sao tome and principe","virgin islands (u.s.)","moldova, republic of","syrian arab republic","united arab emirates","antigua and barbuda","palestine, state of","trinidad and tobago","dominican republic","korea, republic of","russian federation","brunei darussalam","equatorial guinea","wallis and futuna","christmas island","french polynesia","marshall islands","papua new guinea","saint barthélemy","north macedonia","solomon islands","american samoa","cayman islands","norfolk island","western sahara","czech republic","åland islands","bouvet island","côte d'ivoire","faroe islands","french guiana","guinea-bissau","liechtenstein","new caledonia","burkina faso","cook islands","saudi arabia","sierra leone","south africa","turkmenistan","afghanistan","el salvador","isle of man","new zealand","philippines","puerto rico","saint lucia","south sudan","switzerland","timor-leste","south korea","north korea","antarctica","azerbaijan","bangladesh","cabo verde","costa rica","guadeloupe","kazakhstan","kyrgyzstan","luxembourg","madagascar","martinique","mauritania","montenegro","montserrat","mozambique","san marino","seychelles","tajikistan","uzbekistan","argentina","australia","gibraltar","greenland","guatemala","hong kong","indonesia","lithuania","mauritius","nicaragua","singapore","sri lanka","anguilla","barbados","botswana","bulgaria","cambodia","cameroon","colombia","djibouti","dominica","eswatini","ethiopia","guernsey","holy see","honduras","kiribati","malaysia","maldives","mongolia","pakistan","paraguay","pitcairn","portugal","slovakia","slovenia","suriname","thailand","viet nam","zimbabwe","albania","algeria","andorra","armenia","austria","bahamas","bahrain","belarus","belgium","bermuda","burundi","comoros","croatia","curaçao","czechia","denmark","ecuador","eritrea","estonia","finland","georgia","germany","grenada","hungary","iceland","ireland","jamaica","lebanon","lesotho","liberia","mayotte","morocco","myanmar","namibia","nigeria","réunion","romania","senegal","somalia","tokelau","tunisia","türkiye","ukraine","uruguay","vanuatu","angola","belize","bhutan","brazil","canada","cyprus","france","gambia","greece","guinea","guyana","israel","jersey","jordan","kuwait","latvia","malawi","mexico","monaco","norway","panama","poland","rwanda","serbia","sweden","tuvalu","uganda","zambia","russia","aruba","benin","chile","china","congo","egypt","gabon","ghana","haiti","india","italy","japan","kenya","libya","macao","malta","nauru","nepal","niger","palau","qatar","samoa","spain","sudan","tonga","yemen","burma","chad","cuba","fiji","guam","iraq","mali","niue","oman","peru","togo","usa","uk"];
