/**
 * Fallback — sinkron dengan cyber-attack-map-server/payment/checkoutMethods.mjs
 * Hanya metode yang didukung Midtrans.
 */
export const DEFAULT_PAYMENT_METHOD_CATEGORIES = [
  { id: 'ewallet', labelEn: 'E-Wallet', labelId: 'E-Wallet' },
  { id: 'qris', labelEn: 'QRIS', labelId: 'QRIS' },
  { id: 'va', labelEn: 'Bank Transfer', labelId: 'Transfer Bank' },
  { id: 'otc', labelEn: 'Over the Counter', labelId: 'Minimarket' },
  { id: 'card', labelEn: 'Credit / Debit Card', labelId: 'Kartu Kredit / Debit' },
];

export const DEFAULT_PAYMENT_METHODS = [
  {
    id: 'gopay',
    category: 'ewallet',
    brandColor: '#00AED6',
    icon: 'gopay',
    labelEn: 'GoPay',
    labelId: 'GoPay',
    badges: [],
  },
  {
    id: 'shopeepay',
    category: 'ewallet',
    brandColor: '#EE4D2D',
    icon: 'shopeepay',
    labelEn: 'ShopeePay',
    labelId: 'ShopeePay',
    badges: [],
  },
  {
    id: 'qris',
    category: 'qris',
    brandColor: '#E31E24',
    icon: 'qris',
    labelEn: 'QRIS',
    labelId: 'QRIS',
    badges: [],
  },
  {
    id: 'bca_va',
    category: 'va',
    brandColor: '#00529C',
    icon: 'bca',
    labelEn: 'BCA Virtual Account',
    labelId: 'Virtual Account BCA',
    badges: [],
  },
  {
    id: 'bni_va',
    category: 'va',
    brandColor: '#F15A22',
    icon: 'bni',
    labelEn: 'BNI Virtual Account',
    labelId: 'Virtual Account BNI',
    badges: [],
  },
  {
    id: 'bri_va',
    category: 'va',
    brandColor: '#00529C',
    icon: 'bri',
    labelEn: 'BRI Virtual Account',
    labelId: 'Virtual Account BRI',
    badges: [],
  },
  {
    id: 'permata_va',
    category: 'va',
    brandColor: '#00A651',
    icon: 'permata',
    labelEn: 'Permata Virtual Account',
    labelId: 'Virtual Account Permata',
    badges: [],
  },
  {
    id: 'mandiri_va',
    category: 'va',
    brandColor: '#003D79',
    icon: 'mandiri',
    labelEn: 'Mandiri Bill Payment',
    labelId: 'Mandiri Bill Payment',
    badges: [],
  },
  {
    id: 'cimb_va',
    category: 'va',
    brandColor: '#790008',
    icon: 'cimb',
    labelEn: 'CIMB Niaga Virtual Account',
    labelId: 'Virtual Account CIMB Niaga',
    badges: [],
  },
  {
    id: 'indomaret',
    category: 'otc',
    brandColor: '#0054A6',
    icon: 'indomaret',
    labelEn: 'Indomaret',
    labelId: 'Indomaret',
    badges: [],
  },
  {
    id: 'alfamart',
    category: 'otc',
    brandColor: '#ED1C24',
    icon: 'alfamart',
    labelEn: 'Alfamart',
    labelId: 'Alfamart',
    badges: [],
  },
  {
    id: 'credit_card',
    category: 'card',
    brandColor: '#1A1F71',
    icon: 'card',
    labelEn: 'Credit / Debit Card',
    labelId: 'Kartu Kredit / Debit',
    badges: ['visa', 'mastercard', 'jcb', 'amex'],
  },
];
