/**
 * Expanded WAF-style detection signatures for Slark middleware.
 */

/** @param {string} id @param {string} pattern @param {string} [flags] */
function rule(id, pattern, flags = 'i') {
  return { re: new RegExp(pattern, flags), id };
}

/** Build path probe regex at runtime. */
function rx(p, flags = 'i') {
  return new RegExp(p, flags);
}

function dedupeRules(list) {
  const seen = new Set();
  return list.filter((r) => {
    if (seen.has(r.id)) return false;
    seen.add(r.id);
    return true;
  });
}

/** @param {string} fragment */
function scannerPathRule(fragment) {
  const safe = fragment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const id = `path_${fragment.replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '') || 'probe'}`;
  return { re: rx(`^/${safe}(?:/|$|\\?)`), id };
}

export const LOGIN_PATHS = [
  '/login',
  '/signin',
  '/sign-in',
  '/signup',
  '/register',
  '/auth',
  '/authenticate',
  '/session',
  '/oauth',
  '/oauth2',
  '/token',
  '/api/login',
  '/api/auth',
  '/api/signin',
  '/api/session',
  '/api/token',
  '/api/v1/login',
  '/api/v1/auth',
  '/api/v2/login',
  '/admin/login',
  '/admin/signin',
  '/user/login',
  '/account/login',
  '/portal/login',
  '/wp-login.php',
  '/j_spring_security_check',
];

export const SENSITIVE_SCAN_PATHS = [
  '/wp-admin',
  '/wp-login.php',
  '/wp-content',
  '/wp-includes',
  '/xmlrpc.php',
  '/phpmyadmin',
  '/pma',
  '/adminer',
  '/adminer.php',
  '/.env',
  '/.git',
  '/.svn',
  '/.hg',
  '/.DS_Store',
  '/server-status',
  '/server-info',
  '/debug',
  '/trace',
  '/actuator',
  '/actuator/env',
  '/actuator/health',
  '/vendor/phpunit',
  '/boaform',
  '/cgi-bin',
  '/jenkins',
  '/solr',
  '/console',
  '/manager/html',
  '/phpinfo.php',
  '/info.php',
  '/config.php',
  '/backup',
  '/backups',
  '/dump.sql',
  '/database.sql',
  '/.aws',
  '/.docker',
  '/crossdomain.xml',
  '/clientaccesspolicy.xml',
  '/telescope',
  '/horizon',
  '/_profiler',
  '/graphql',
  '/swagger',
  '/api-docs',
  '/.well-known/security.txt',
];

const SCANNER_PATH_FRAGMENTS = [
  ...SENSITIVE_SCAN_PATHS.map((p) => p.replace(/^\//, '')),
  'admin/config',
  'administrator',
  'cpanel',
  'webmail',
  'shell',
  'cmd',
  'eval-stdin.php',
  'vendor/laravel',
  'storage/logs',
  'laravel.log',
  'debug/default/view',
  'elmah.axd',
  'aws/credentials',
  'id_rsa',
  'id_dsa',
  'authorized_keys',
  'web.config',
  'appsettings.json',
  'settings.py',
  'secrets.json',
  'credentials.json',
  'docker-compose.yml',
  'kubeconfig',
  'terraform.tfstate',
  'sftp-config.json',
  'composer.json',
  'package-lock.json',
  'yarn.lock',
  'readme.md',
  'license.txt',
  'install.php',
  'setup.php',
  'upgrade.php',
  'test.php',
  'phpunit',
  'owa/auth',
  'exchange',
  'autodiscover',
  'remote/login',
  'dana-na',
  'HNAP1',
  'sdk',
  'evox/about',
  'nmaplowercheck',
];

export const SCANNER_PATH_RULES = dedupeRules(SCANNER_PATH_FRAGMENTS.map(scannerPathRule));

export const SQLI_RULES = dedupeRules([
  rule('or_tautology_quote', '\'\\s*or\\s+[\'\\"]?\\d*[\'\\"]?\\s*=\\s*[\'\\"]?\\d*', 'i'),
  rule('or_1_1', '\'\\s*or\\s+[\'\\"]?1[\'\\"]?\\s*=\\s*[\'\\"]?1', 'i'),
  rule('or_dquote_tautology', '"\\s*or\\s+"?\\d+"?\\s*=\\s*"?\\d*', 'i'),
  { re: rx(/--[\s#]/), id: 'sql_comment_dash' },
  rule('mysql_version_comment', '/\\*!\\d', 'i'),
  rule('block_comment', '/\\*[\\s\\S]{0,40}\\*/', 'i'),
  rule('hash_comment_sqli', '#\\s*(?:select|union|sleep|benchmark)\\b', 'i'),
  rule('union_select', '\\bunion\\s+[\\w*(),\\s]{0,120}\\bselect\\b', 'i'),
  rule('union_all_select', '\\bunion\\s+all\\s+select\\b', 'i'),
  rule('select_from', '\\bselect\\s+.{1,160}\\bfrom\\b', 'is'),
  rule('select_where', '\\bselect\\s+.{1,80}\\bwhere\\b', 'is'),
  rule('insert_into', '\\binsert\\s+into\\b', 'i'),
  rule('update_set', '\\bupdate\\s+\\w+\\s+set\\b', 'i'),
  rule('delete_from', '\\bdelete\\s+from\\b', 'i'),
  rule('drop_object', '\\bdrop\\s+(?:table|database|schema)\\b', 'i'),
  rule('truncate_table', '\\btruncate\\s+table\\b', 'i'),
  rule('alter_table', '\\balter\\s+table\\b', 'i'),
  rule('create_object', '\\bcreate\\s+(?:table|database)\\b', 'i'),
  rule('into_outfile', '\\binto\\s+outfile\\b', 'i'),
  rule('into_dumpfile', '\\binto\\s+dumpfile\\b', 'i'),
  rule('load_file', '\\bload_file\\s*\\(', 'i'),
  rule('outfile_fn', '\\boutfile\\s*\\(', 'i'),
  rule('info_schema', '\\binformation_schema\\.(?:tables|columns|schemata)\\b', 'i'),
  rule('mysql_system', '\\bmysql\\.(?:user|db)\\b', 'i'),
  rule('pg_catalog', '\\bpg_catalog\\.', 'i'),
  rule('mssql_sys', '\\bsys\\.(?:tables|databases)\\b', 'i'),
  rule('sleep_fn', '\\bsleep\\s*\\(\\s*\\d+', 'i'),
  rule('pg_sleep', '\\bpg_sleep\\s*\\(', 'i'),
  rule('waitfor_delay', '\\bwaitfor\\s+delay\\b', 'i'),
  rule('benchmark', '\\bbenchmark\\s*\\(', 'i'),
  rule('get_lock', '\\bget_lock\\s*\\(', 'i'),
  rule('extractvalue', '\\bextractvalue\\s*\\(', 'i'),
  rule('updatexml', '\\bupdatexml\\s*\\(', 'i'),
  rule('exp_dos', '\\bexp\\s*\\(\\s*~', 'i'),
  rule('or_tautology', '\\bor\\s+[\\\'"]?\\d+[\\\'"]?\\s*=\\s*[\\\'"]?\\d+', 'i'),
  rule('or_string_tautology', '\'\\s*or\\s+\'\\d+\'\\s*=\\s*\'', 'i'),
  rule('and_false', '\\band\\s+1\\s*=\\s*0\\b', 'i'),
  rule('and_true', '\\band\\s+1\\s*=\\s*1\\b', 'i'),
  rule('or_true_numeric', '\\bor\\s+1\\s*=\\s*1\\b', 'i'),
  rule('having_tautology', '\\bhaving\\s+1\\s*=\\s*1\\b', 'i'),
  rule('group_by_num', '\\bgroup\\s+by\\s+\\d+\\b', 'i'),
  rule('order_by_num', '\\border\\s+by\\s+\\d+\\b', 'i'),
  rule('order_by_comment', '\\border\\s+by\\s+\\d+\\s*--', 'i'),
  rule('case_when', '\\bcase\\s+when\\b', 'i'),
  rule('if_tautology', '\\bif\\s*\\(\\s*\\d+\\s*=\\s*\\d+', 'i'),
  rule('char_fn', '\\bchar\\s*\\(\\s*\\d+', 'i'),
  rule('concat_fn', '\\bconcat\\s*\\(', 'i'),
  rule('group_concat', '\\bgroup_concat\\s*\\(', 'i'),
  rule('hex_literal', '\\b0x[0-9a-f]{4,}', 'i'),
  rule('cast_fn', '\\bcast\\s*\\(', 'i'),
  rule('convert_fn', '\\bconvert\\s*\\(', 'i'),
  rule('at_version', '\\b@@version\\b', 'i'),
  rule('at_datadir', '\\b@@datadir\\b', 'i'),
  rule('user_fn', '\\buser\\s*\\(\\s*\\)', 'i'),
  rule('database_fn', '\\bdatabase\\s*\\(\\s*\\)', 'i'),
  rule('schema_fn', '\\bschema\\s*\\(\\s*\\)', 'i'),
  rule('version_fn', '\\bversion\\s*\\(\\s*\\)', 'i'),
  rule('mssql_exec', '\\bexec\\s*\\(\\s*xp_', 'i'),
  rule('xp_cmdshell', '\\bxp_cmdshell\\b', 'i'),
  rule('sp_configure', '\\bsp_configure\\b', 'i'),
  rule('openrowset', '\\bopenrowset\\b', 'i'),
  rule('opendatasource', '\\bopendatasource\\b', 'i'),
  rule('mssql_declare', '\\bdeclare\\s+@', 'i'),
  rule('stacked_query', ';\\s*(?:drop|delete|truncate|update|insert)\\b', 'i'),
  rule('procedure_analyse', '\\bprocedure\\s+analyse\\b', 'i'),
  rule('json_extract', '\\bjson_extract\\b', 'i'),
  rule('substr_version', '\\bsubstr(?:ing)?\\s*\\(\\s*@@', 'i'),
  rule('encoded_quote_logic', '%27\\s*(?:or|and)\\s*%27', 'i'),
  rule('double_encoded_quote', '%2527', 'i'),
  rule('unicode_quote', '%u0027', 'i'),
  rule('hex_quote_logic', '\\x27.*(?:or|and)', 'i'),
  rule('admin_comment', 'admin\'\\s*--', 'i'),
  rule('quote_semi_comment', '\'\\s*;\\s*--', 'i'),
  rule('or_true_kw', '\\bor\\s+true\\b', 'i'),
  rule('like_wildcard', '\\blike\\s+[\\\'"]%', 'i'),
  rule('limit_offset', '\\blimit\\s+\\d+\\s*,\\s*\\d+', 'i'),
  rule('count_star', '\\bcount\\s*\\(\\s*\\*\\s*\\)', 'i'),
]);

export const XSS_RULES = dedupeRules([
  rule('script_tag', '<\\s*script\\b', 'i'),
  rule('close_script', '<\\s*/\\s*script\\b', 'i'),
  rule('script_alert', '<\\s*script[^>]*>\\s*alert\\s*\\(', 'i'),
  rule('script_confirm', '<\\s*script[^>]*>\\s*confirm\\s*\\(', 'i'),
  rule('script_prompt', '<\\s*script[^>]*>\\s*prompt\\s*\\(', 'i'),
  rule('javascript_uri', 'javascript\\s*:', 'i'),
  rule('vbscript_uri', 'vbscript\\s*:', 'i'),
  rule('data_html', 'data\\s*:\\s*text\\/html', 'i'),
  rule('data_js', 'data\\s*:\\s*text\\/javascript', 'i'),
  rule('event_handler', '<\\s*[^>]{0,160}\\bon\\w+\\s*=\\s*[\\\'"]?', 'i'),
  rule('iframe_tag', '<\\s*iframe\\b', 'i'),
  rule('frame_tag', '<\\s*frame\\b', 'i'),
  rule('object_tag', '<\\s*object\\b', 'i'),
  rule('embed_tag', '<\\s*embed\\b', 'i'),
  rule('applet_tag', '<\\s*applet\\b', 'i'),
  rule('meta_refresh', '<\\s*meta\\b[^>]{0,120}http-equiv', 'i'),
  rule('link_import', '<\\s*link\\b[^>]{0,120}rel\\s*=\\s*[\\\'"]?stylesheet', 'i'),
  rule('base_tag', '<\\s*base\\b', 'i'),
  rule('form_action', '<\\s*form\\b[^>]{0,120}action', 'i'),
  rule('hidden_input', '<\\s*input\\b[^>]{0,120}type\\s*=\\s*[\\\'"]?hidden', 'i'),
  rule('svg_onhandler', '<\\s*svg\\b[^>]{0,200}\\bon\\w+', 'i'),
  rule('math_tag', '<\\s*math\\b', 'i'),
  rule('video_onhandler', '<\\s*video\\b[^>]{0,120}\\bon', 'i'),
  rule('audio_onhandler', '<\\s*audio\\b[^>]{0,120}\\bon', 'i'),
  rule('details_onhandler', '<\\s*details\\b[^>]{0,120}\\bon', 'i'),
  rule('marquee_tag', '<\\s*marquee\\b', 'i'),
  rule('body_onhandler', '<\\s*body\\b[^>]{0,120}\\bon', 'i'),
  rule('img_onerror', '<\\s*img\\b[^>]{0,160}\\bonerror\\b', 'i'),
  rule('img_onload', '<\\s*img\\b[^>]{0,160}\\bonsrc\\b', 'i'),
  rule('source_onhandler', '<\\s*source\\b[^>]{0,120}\\bon', 'i'),
  rule('eval_literal', '\\beval\\s*\\(\\s*[\'"`]', 'i'),
  rule('settimeout_string', '\\bsetTimeout\\s*\\(\\s*[\'"`]', 'i'),
  rule('setinterval_string', '\\bsetInterval\\s*\\(\\s*[\'"`]', 'i'),
  rule('function_ctor', 'Function\\s*\\(\\s*[\'"`]', 'i'),
  rule('from_char_code', 'String\\.fromCharCode\\s*\\(', 'i'),
  rule('document_sink', 'document\\.(cookie|write|domain|location)\\b', 'i'),
  rule('window_sink', 'window\\.(location|document|open)\\b', 'i'),
  rule('location_sink', 'location\\.(href|assign|replace)\\b', 'i'),
  rule('storage_sink', 'localStorage\\.|sessionStorage\\.', 'i'),
  rule('alert_probe', '\\balert\\s*\\(\\s*[\\\'"\\d]', 'i'),
  rule('dialog_probe', '\\b(?:prompt|confirm)\\s*\\(', 'i'),
  rule('console_probe', '\\bconsole\\.log\\s*\\(', 'i'),
  rule('inline_alert', '\\bon\\w+\\s*=\\s*alert\\b', 'i'),
  rule('inline_eval', '\\bon\\w+\\s*=\\s*eval\\b', 'i'),
  rule('encoded_script', '%3[Cc]\\s*script', 'i'),
  rule('encoded_iframe', '%3[Cc]\\s*iframe', 'i'),
  rule('hex_script', '\\x3c\\s*script', 'i'),
  rule('unicode_script', '\\u003c\\s*script', 'i'),
  rule('entity_script', '&lt;\\s*script', 'i'),
  rule('numeric_entity_script', '&#x?[0-9a-f]+;\\s*script', 'i'),
  rule('cdata_script', '<!\\[CDATA\\[[\\s\\S]{0,80}script', 'i'),
  rule('css_expression', 'expression\\s*\\(', 'i'),
  rule('moz_binding', '-moz-binding\\s*:', 'i'),
  rule('css_js_url', 'url\\s*\\(\\s*javascript', 'i'),
  rule('css_import_js', '@import\\s+[\\\'"]?javascript', 'i'),
  rule('style_expression', '<style[^>]{0,120}>[\\s\\S]{0,200}expression', 'i'),
  rule('iframe_srcdoc', 'srcdoc\\s*=', 'i'),
  rule('formaction', 'formaction\\s*=', 'i'),
  rule('xlink_js', 'xlink:href\\s*=\\s*[\\\'"]?javascript', 'i'),
  rule('xmlns_js', 'xmlns\\s*=\\s*[\\\'"]?javascript', 'i'),
  rule('json_onhandler', '\\[\\s*[\\\'"]on\\w+', 'i'),
  rule('title_breakout', '</\\s*title\\s*><\\s*script', 'i'),
  rule('textarea_breakout', '</\\s*textarea\\s*><\\s*script', 'i'),
  rule('style_breakout', '</\\s*style\\s*><\\s*script', 'i'),
  rule('external_script', '<\\s*script[^>]+src\\s*=\\s*[\\\'"]?//', 'i'),
  rule('fetch_call', 'fetch\\s*\\(\\s*[\'"`]', 'i'),
  rule('xhr_ctor', 'XMLHttpRequest\\s*\\(', 'i'),
  rule('send_beacon', 'navigator\\.sendBeacon', 'i'),
  rule('dynamic_import', 'import\\s*\\(\\s*[\'"`]', 'i'),
  rule('atob_decode', 'atob\\s*\\(', 'i'),
  rule('btoa_encode', 'btoa\\s*\\(', 'i'),
  rule('self_bracket', 'self\\[', 'i'),
  rule('top_bracket', 'top\\[', 'i'),
  rule('parent_bracket', 'parent\\[', 'i'),
  rule('proto_pollution', '__proto__', 'i'),
  rule('constructor_proto', 'constructor\\s*\\[\\s*[\\\'"]prototype', 'i'),
  rule('isindex_tag', '<\\s*isindex\\b', 'i'),
  rule('keygen_tag', '<\\s*keygen\\b', 'i'),
  rule('pointer_raw_update', 'onpointerrawupdate', 'i'),
  rule('animation_start', 'onanimationstart', 'i'),
  rule('focusin_handler', 'onfocusin', 'i'),
  rule('toggle_handler', 'ontoggle', 'i'),
  rule('dbl_enc_script_break', '%22%3e%3cscript', 'i'),
  rule('quote_break_script', '"><\\s*script', 'i'),
  rule('squote_break_script', '\'\\s*>\\s*<\\s*script', 'i'),
  rule('svg_shorthand', '<svg/onload', 'i'),
  rule('img_shorthand', '<img/src/onerror', 'i'),
  rule('entity_colon_js', 'javascript&colon;', 'i'),
]);

export const PATH_TRAVERSAL_RULES = dedupeRules([
  rule('dot_dot_slash', '\\.\\.[\\/\\\\]', 'i'),
  rule('dot_dot_backslash', '\\.\\.\\\\', 'i'),
  rule('encoded_traversal', '%2e%2e(?:%2f|%5c)|%252e%252e', 'i'),
  rule('overlong_utf8_traversal', '%c0%ae%c0%ae', 'i'),
  rule('mixed_encoded_traversal', '\\.\\.%2f', 'i'),
  rule('mixed_encoded_backslash', '\\.\\.%5c', 'i'),
  rule('etc_passwd', 'etc\\/passwd|etc%2fpasswd', 'i'),
  rule('etc_shadow', 'etc\\/shadow|etc%2fshadow', 'i'),
  rule('proc_environ', 'proc\\/self\\/environ', 'i'),
  rule('proc_cmdline', 'proc\\/self\\/cmdline', 'i'),
  rule('win_system32', 'windows\\/system32', 'i'),
  rule('win_ini', 'win\\.ini', 'i'),
  rule('boot_ini', 'boot\\.ini', 'i'),
  rule('sam_registry', 'sam\\s*\\\\', 'i'),
  rule('system_ini', 'system\\.ini', 'i'),
  rule('var_log', '\\/var\\/log\\/', 'i'),
  rule('root_dir', '\\/root\\/', 'i'),
  rule('home_dir', '\\/home\\/[^/]+\\/', 'i'),
  rule('drive_letter', 'c:\\\\', 'i'),
  rule('file_uri', 'file:\\/\\/\\/', 'i'),
  rule('double_traversal', '\\.\\.\\/\\.\\.\\/', 'i'),
  rule('null_trunc_traversal', '\\.\\.%00', 'i'),
  rule('null_prefix_traversal', '%00\\.\\.', 'i'),
  rule('semicolon_traversal', '\\.\\.;\\/', 'i'),
  rule('triple_dot_slash', '\\.\\.\\.\\/\\/', 'i'),
  rule('middle_traversal', '\\/\\.\\.\\/', 'i'),
]);

export const FILE_INCLUSION_RULES = dedupeRules([
  rule('param_local_traversal', '\\b(?:file|page|include|template|view|module|lang|path|doc|folder|dir|document|layout|theme|skin)=.{0,200}(?:\\.\\.[\\/\\\\]|%2e%2e)', 'i'),
  rule('param_sensitive_file', '\\b(?:file|page|include|template|view|module|lang|path)=.{0,160}(?:etc\\/passwd|win\\.ini)', 'i'),
  rule('param_remote_url', '\\b(?:file|page|include|template|view|module|lang|path)=.{0,140}(?:https?:\\/\\/|ftp:\\/\\/|ftps:\\/\\/)', 'i'),
  rule('param_wrapper', '\\b(?:file|page|include|template|view|module|lang|path)=.{0,120}(?:php:\\/\\/|file:\\/\\/|zip:\\/\\/|phar:\\/\\/|data:\\/\\/|expect:\\/\\/|glob:\\/\\/)', 'i'),
  rule('php_require_remote', '\\brequire(?:_once)?\\s*\\(\\s*[\\\'"]https?:', 'i'),
  rule('php_include_remote', '\\binclude(?:_once)?\\s*\\(\\s*[\\\'"]https?:', 'i'),
  rule('readfile_remote', '\\breadfile\\s*\\(\\s*[\\\'"]https?:', 'i'),
  rule('fopen_remote', '\\bfopen\\s*\\(\\s*[\\\'"]https?:', 'i'),
  rule('fgc_remote', '\\bfile_get_contents\\s*\\(\\s*[\\\'"]https?:', 'i'),
  rule('php_filter_wrapper', '\\bphp://filter', 'i'),
  rule('php_input_wrapper', '\\bphp://input', 'i'),
  rule('zip_wrapper', '\\bzip://', 'i'),
  rule('phar_wrapper', '\\bphar://', 'i'),
  rule('expect_wrapper', '\\bexpect://', 'i'),
  rule('data_base64', '\\bdata://text\\/plain;base64,', 'i'),
  rule('lfi_passwd', '\\b\\/etc\\/passwd\\b', 'i'),
  rule('lfi_proc_self', '\\b\\/proc\\/self\\/', 'i'),
  rule('lfi_windows', '\\bC:\\\\Windows\\\\', 'i'),
  rule('deep_traversal_param', '\\.\\./\\.\\./\\.\\./', 'i'),
  rule('lang_traversal', 'lang=\\.\\./', 'i'),
  rule('template_traversal', 'template=\\.\\./', 'i'),
  rule('page_wrapper', 'page=php://', 'i'),
  rule('module_wrapper', 'module=php://', 'i'),
  rule('path_traversal_param', 'path=\\.\\./', 'i'),
  rule('document_traversal', 'document=\\.\\./', 'i'),
  rule('load_traversal', 'load=\\.\\./', 'i'),
  rule('style_traversal', 'style=\\.\\./', 'i'),
  rule('config_traversal', 'config=\\.\\./', 'i'),
  rule('resource_traversal', 'resource=\\.\\./', 'i'),
  rule('asset_traversal', 'asset=\\.\\./', 'i'),
  rule('redirect_traversal', 'redirect=\\.\\./', 'i'),
  rule('return_traversal', 'return=\\.\\./', 'i'),
]);

export const CMD_INJECTION_RULES = dedupeRules([
  rule('shell_metachar', '[;&]\\s*(?:ls|cat|rm|wget|curl|nc\\b|netcat|bash|sh\\b|cmd\\.exe|powershell|ping|whoami|id|uname|hostname|ifconfig|ipconfig)\\b', 'i'),
  rule('and_and_cmd', '&&\\s*\\w+', 'i'),
  rule('or_or_cmd', '\\|\\|\\s*\\w+', 'i'),
  rule('pipe_cmd', '\\|\\s*(?:cat|ls|sh|bash|nc\\b|wget|curl|whoami|id)\\b', 'i'),
  rule('backtick', '`[^`\\n]{1,160}`', 'i'),
  rule('dollar_subshell', '\\\\$\\([^)\\n]{1,120}\\)', 'i'),
  rule('brace_subshell', '\\\\$\\{[^}\\n]{1,80}\\}', 'i'),
  rule('pipe_sh', '\\|\\s*sh\\b', 'i'),
  rule('pipe_bash', '\\|\\s*bash\\b', 'i'),
  rule('semi_bin', ';\\s*\\/bin\\/', 'i'),
  rule('semi_usr_bin', ';\\s*\\/usr\\/bin\\/', 'i'),
  rule('bin_sh', '\\b/bin\\/sh\\b', 'i'),
  rule('bin_bash', '\\b/bin\\/bash\\b', 'i'),
  rule('cmd_exe', '\\bcmd\\.exe\\b', 'i'),
  rule('powershell', '\\bpowershell(?:\\.exe)?\\b', 'i'),
  rule('pwsh', '\\bpwsh\\b', 'i'),
  rule('whoami', '\\bwhoami\\b', 'i'),
  rule('net_user', '\\bnet\\s+user\\b', 'i'),
  rule('net_localgroup', '\\bnet\\s+localgroup\\b', 'i'),
  rule('ipconfig', '\\bipconfig\\b', 'i'),
  rule('ifconfig', '\\bifconfig\\b', 'i'),
  rule('nslookup', '\\bnslookup\\b', 'i'),
  rule('dig', '\\bdig\\s+', 'i'),
  rule('chmod', '\\bchmod\\s+', 'i'),
  rule('chown', '\\bchown\\s+', 'i'),
  rule('tar', '\\btar\\s+-', 'i'),
  rule('python_c', '\\bpython\\s+-c\\b', 'i'),
  rule('perl_e', '\\bperl\\s+-e\\b', 'i'),
  rule('ruby_e', '\\bruby\\s+-e\\b', 'i'),
  rule('node_e', '\\bnode\\s+-e\\b', 'i'),
  rule('php_r', '\\bphp\\s+-r\\b', 'i'),
  rule('base64_decode_cmd', '\\bbase64\\s+-d\\b', 'i'),
  rule('eval_cmd', '\\beval\\s+', 'i'),
  rule('sudo', '\\bsudo\\s+', 'i'),
  rule('su_dash', '\\bsu\\s+-', 'i'),
  rule('kill', '\\bkill(?:all)?\\s+-', 'i'),
  rule('ps_aux', '\\bps\\s+aux\\b', 'i'),
  rule('top_cmd', '\\btop\\b', 'i'),
  rule('env_cmd', '\\benv\\b', 'i'),
  rule('printenv', '\\bprintenv\\b', 'i'),
  rule('export_cmd', '\\bexport\\s+', 'i'),
  rule('curl_flags', '\\bcurl\\s+-', 'i'),
  rule('wget_flags', '\\bwget\\s+-', 'i'),
  rule('nc_flags', '\\bnc\\s+-', 'i'),
  rule('ncat', '\\bncat\\s+', 'i'),
  rule('telnet', '\\btelnet\\s+', 'i'),
  rule('ssh', '\\bssh\\s+', 'i'),
  rule('scp', '\\bscp\\s+', 'i'),
  rule('rm_rf', '\\brm\\s+-rf\\b', 'i'),
  rule('dd_if', '\\bdd\\s+if=', 'i'),
  rule('mkfifo', '\\bmkfifo\\b', 'i'),
  rule('dev_tcp', '\\b\\/dev\\/tcp\\/', 'i'),
  rule('dev_udp', '\\b\\/dev\\/udp\\/', 'i'),
  rule('newline_cmd', '%0a(?:cat|ls|id|whoami|wget|curl)\\b', 'i'),
  rule('crlf_cmd', '%0d%0a(?:cat|ls|id)\\b', 'i'),
]);

export const AUTH_BYPASS_RULES = dedupeRules([
  rule('rewrite_override', '\\b(?:x-original-url|x-rewrite-url|x-forwarded-uri|x-uri)\\b', 'i'),
  rule('method_override_hdr', '\\b(?:x-http-method-override|x-method-override)\\b', 'i'),
  rule('method_override_val', '\\b(?:x-http-method-override)\\s*[:=]\\s*(?:put|patch|delete|trace)\\b', 'i'),
  rule('underscore_method', '\\b_x_method\\s*=\\s*(?:put|delete|patch)\\b', 'i'),
  rule('privilege_param', '\\b(?:role|isadmin|is_admin|admin|access_level|scope|impersonate|sudo|superuser)\\s*[:=]\\s*(?:1|true|admin|root|superuser)\\b', 'i'),
  rule('id_override', '\\b(?:user_id|uid|account_id)\\s*=\\s*(?:0|1|admin)\\b', 'i'),
  rule('token_bypass', '\\b(?:jwt|token|api_key|apikey|secret)\\s*=\\s*[\\\'"]?(?:null|none|undefined|admin)', 'i'),
  rule('privileged_path', '\\b(?:\\/admin(?:\\/|\\$)|\\/internal(?:\\/|\\$)|\\/private(?:\\/|\\$)|\\/actuator(?:\\/|\\$)|\\/debug(?:\\/|\\$))', 'i'),
  rule('acme_traversal', '\\b\\/\\.well-known\\/acme-challenge\\/\\.\\.', 'i'),
  rule('bearer_null', '\\bauthorization\\s*:\\s*bearer\\s+(?:null|none|undefined)\\b', 'i'),
  rule('basic_admin', '\\bauthorization\\s*:\\s*basic\\s+[a-z0-9+/=]{0,20}admin', 'i'),
  rule('api_key_test', '\\bx-api-key\\s*:\\s*(?:test|admin|null)', 'i'),
  rule('auth_token_bypass', '\\bx-auth-token\\s*:\\s*(?:bypass|admin|null)', 'i'),
  rule('debug_true', '\\bdebug\\s*=\\s*true\\b', 'i'),
  rule('test_flag', '\\btest\\s*=\\s*1\\b', 'i'),
  rule('no_auth_flag', '\\bno_auth\\s*=\\s*1\\b', 'i'),
  rule('skip_auth_flag', '\\bskip_auth\\s*=\\s*1\\b', 'i'),
  rule('bypass_flag', '\\bbypass\\s*=\\s*1\\b', 'i'),
  rule('auth_true_param', '\\bauthenticated\\s*=\\s*true\\b', 'i'),
  rule('login_as', '\\blogin_as\\s*=', 'i'),
  rule('impersonate_param', '\\bimpersonate\\s*=', 'i'),
  rule('custom_ip_auth', '\\bX-Custom-IP-Authorization\\b', 'i'),
  rule('fwd_host_localhost', '\\bX-Forwarded-Host\\s*:\\s*localhost', 'i'),
  rule('original_host', '\\bX-Original-Host\\s*:\\s*', 'i'),
  rule('rewrite_admin', '\\bX-Rewrite-URL\\s*:\\s*\\/admin', 'i'),
  rule('original_admin', '\\bX-Original-URL\\s*:\\s*\\/admin', 'i'),
  rule('override_url', '\\bX-Override-URL\\s*:\\s*', 'i'),
  rule('proxy_user_ip', '\\bX-ProxyUser-Ip\\s*:\\s*127\\.0\\.0\\.1', 'i'),
  rule('client_ip_spoof', '\\bClient-IP\\s*:\\s*127\\.0\\.0\\.1', 'i'),
  rule('true_client_ip_spoof', '\\bTrue-Client-IP\\s*:\\s*127\\.0\\.0\\.1', 'i'),
  rule('access_token_admin', '\\baccess_token=admin\\b', 'i'),
  rule('weak_password_probe', '\\bpassword=\\s*(?:\\\'|\\")?(?:admin|password|123456)', 'i'),
]);

export const SUSPICIOUS_REQUEST_RULES = dedupeRules([
  rule('null_byte', '%00|\\0', 'i'),
  rule('double_encoded', '%25(?:32|33|34|35|36|37|38|39)', 'i'),
  rule('double_encoded_slash', '%252f|%255c', 'i'),
  rule('malformed_probe', '\\b(?:\\*\\/\\*|\\.\\.\\/\\.\\.\\/|%2f%2f|\\/\\/\\/|__proto__|constructor\\.)', 'i'),
  rule('unsafe_method_probe', '\\b(?:trace|track)\\b', 'i'),
  rule('prototype_assign', '\\bprototype\\s*=\\s*\\{', 'i'),
  rule('define_getter', '\\b__defineGetter__\\b', 'i'),
  rule('define_setter', '\\b__defineSetter__\\b', 'i'),
  rule('object_assign_json', '\\bObject\\.assign\\s*\\(\\s*\\{\\s*\\},\\s*JSON', 'i'),
  rule('log4j_jndi', '\\\\$\\{jndi:', 'i'),
  rule('template_env', '\\\\$\\{env:', 'i'),
  rule('template_sys', '\\\\$\\{sys:', 'i'),
  rule('template_lower', '\\\\$\\{lower:', 'i'),
  rule('template_upper', '\\\\$\\{upper:', 'i'),
  rule('struts_ognl', '%\\{[^}]{1,80}\\}', 'i'),
  rule('el_injection', '#\\s*\\{\\s*', 'i'),
  rule('template_literal', '\\\\$\\{\\s*', 'i'),
  rule('erb_output', '<%\\s*=\\s*', 'i'),
  rule('freemarker_assign', '<#\\s*assign', 'i'),
  rule('velocity_ref', '\\[\\[\\s*\\\\$\\{', 'i'),
  rule('expression_lang', '@\\s*\\(\\s*[\\\'"]', 'i'),
  rule('b64_decode_fn', '\\bbase64_decode\\s*\\(', 'i'),
  rule('gzinflate', '\\bgzinflate\\s*\\(', 'i'),
  rule('gzuncompress', '\\bgzuncompress\\s*\\(', 'i'),
  rule('php_assert', '\\bassert\\s*\\(\\s*\\\\$', 'i'),
  rule('create_function', '\\bcreate_function\\s*\\(', 'i'),
  rule('preg_replace_e', '\\bpreg_replace\\s*\\([^)]*\\/e', 'i'),
  rule('call_user_func', '\\bcall_user_func\\s*\\(', 'i'),
  rule('system_fn', '\\bsystem\\s*\\(', 'i'),
  rule('shell_exec', '\\bshell_exec\\s*\\(', 'i'),
  rule('passthru', '\\bpassthru\\s*\\(', 'i'),
  rule('proc_open', '\\bproc_open\\s*\\(', 'i'),
  rule('popen', '\\bpopen\\s*\\(', 'i'),
  rule('pcntl_exec', '\\bpcntl_exec\\s*\\(', 'i'),
  rule('move_uploaded', '\\bmove_uploaded_file\\b', 'i'),
  rule('dangerous_upload', 'multipart\\/form-data.*filename=.*\\.(?:php|phtml|phar|asp|aspx|jsp)', 'i'),
  rule('php_content_type', 'Content-Type:\\s*application\\/x-php', 'i'),
  rule('null_in_path', '\\.\\.%00\\.', 'i'),
  rule('charset_ibm037', 'charset=ibm037', 'i'),
  rule('utf7', 'utf-7', 'i'),
  rule('utf7_encoded', '%ADd', 'i'),
  rule('raw_null', '\\x00', 'i'),
  rule('control_chars', '[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f]', 'i'),
  rule('inline_select', '\\bSELECT\\b.{0,40}\\bFROM\\b', 'is'),
  rule('inline_script', '<script', 'i'),
  rule('inline_onerror', 'onerror\\s*=', 'i'),
  rule('inline_javascript', 'javascript:', 'i'),
  rule('inline_traversal', '\\.\\./\\.\\./', 'i'),
  rule('inline_mysql_comment', '\\/\\*\\!', 'i'),
  rule('inline_union', 'union\\s+select', 'i'),
  rule('inline_cmd', 'cmd\\.exe', 'i'),
  rule('inline_passwd', '/etc/passwd', 'i'),
  rule('inline_php_wrapper', 'php://', 'i'),
  rule('inline_template', '\\\\${', 'i'),
  rule('inline_jndi', 'jndi:ldap', 'i'),
  rule('inline_proto', '__proto__', 'i'),
  rule('inline_base64', 'base64,', 'i'),
  rule('unicode_escape', '%u00', 'i'),
  rule('hex_escape', '\\x[0-9a-f]{2}', 'i'),
  rule('html_entity', '&#[0-9]{2,5};', 'i'),
  rule('trace_method', '\\bTRACE\\b', 'i'),
  rule('track_method', '\\bTRACK\\b', 'i'),
]);

const UA_TOOL_PATTERNS = [
  'sqlmap', 'nikto', 'nmap', 'masscan', 'zgrab', 'wpscan', 'acunetix', 'nessus', 'openvas',
  'qualys', 'burp', 'burpsuite', 'owasp zap', 'zaproxy', 'arachni', 'skipfish', 'w3af',
  'dirbuster', 'dirb', 'gobuster', 'ffuf', 'feroxbuster', 'wfuzz', 'hydra', 'medusa',
  'metasploit', 'msf', 'nuclei', 'httpx', 'subfinder', 'amass', 'shodan', 'censys',
  'curl', 'wget', 'python-requests', 'python-urllib', 'aiohttp', 'httplib2', 'libwww-perl',
  'lwp-trivial', 'go-http-client', 'java/', 'apache-httpclient', 'okhttp', 'axios',
  'node-fetch', 'undici', 'postmanruntime', 'insomnia', 'httpie', 'rest-client',
  'headlesschrome', 'headless', 'phantomjs', 'playwright', 'puppeteer', 'selenium',
  'webdriver', 'scrapy', 'mechanize', 'httpclient', 'winhttp', 'powershell',
  'googlebot', 'bingbot', 'baiduspider', 'yandexbot', 'petalbot', 'semrushbot',
  'ahrefsbot', 'mj12bot', 'dotbot', 'bytespider', 'gptbot', 'claudebot', 'ccbot',
  'masscan', 'zmap', 'nmap scripting engine', 'whatweb', 'jaeles', 'dalfox', 'xsstrike',
  'commix', 'tplmap', 'fimap', 'uniscan', 'paros', 'webscarab', 'vega', 'grabber',
  'havij', 'pangolin', 'absinthe', 'sqlninja', 'bbscan', 'xray', 'gau', 'gauri', 'waybackurls',
  'hakrawler', 'meg', 'jaeles', 'nmap', 'spider', 'crawler', 'scan', 'exploit',
  'vulnerability', 'securityscan', 'netsparker', 'appscan', 'webinspect', 'arachni',
];

export const DEFAULT_UA_BLOCK = dedupeRules(
  UA_TOOL_PATTERNS.map((name) => ({
    re: rx(name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')),
    id: name.replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '') || 'ua_tool',
  })),
);

/** Behavioral bot signals (empty UA, missing accept headers, etc.) */
export const BOT_ACTIVITY_RULES = [
  { test: (ctx) => !ctx.ua || ctx.ua.trim().length === 0, id: 'empty_ua' },
  { test: (ctx) => ctx.ua.trim().length > 0 && ctx.ua.trim().length < 12, id: 'short_ua' },
  { test: (ctx) => /^[a-z0-9._-]+$/i.test(ctx.ua) && ctx.ua.length < 24, id: 'minimal_ua_token' },
  { test: (ctx) => /\b(bot|crawler|spider|scraper|scan|probe)\b/i.test(ctx.ua), id: 'ua_bot_keyword' },
  { test: (ctx) => ctx.method === 'GET' && !ctx.headerBlob.includes('accept'), id: 'missing_accept' },
  { test: (ctx) => ctx.method === 'GET' && !ctx.headerBlob.includes('accept-language'), id: 'missing_accept_language' },
  { test: (ctx) => /^(?:GET|HEAD)\s+\//i.test(ctx.pathQuery) && ctx.ua === 'Mozilla/5.0', id: 'fake_mozilla_minimal' },
];

/** Default rate-limit profiles (tighter than legacy defaults). */
export const BEHAVIOR_RATE_DEFAULTS = {
  ddos: { maxPerWindow: 90, windowMs: 10_000 },
  bruteForce: { maxPerWindow: 8, windowMs: 60_000 },
  scanner: { maxPerWindow: 10, windowMs: 60_000 },
  botActivity: { maxPerWindow: 35, windowMs: 30_000 },
  suspiciousRequest: { maxPerWindow: 6, windowMs: 60_000 },
};

/**
 * @param {ReturnType<typeof import('./detectionMiddleware.mjs').collectScanContext>} ctx
 */
export function detectBotActivity(ctx) {
  for (const rule of BOT_ACTIVITY_RULES) {
    if (rule.test(ctx)) return { id: rule.id };
  }
  return null;
}

const SCANNER_UA_IDS = new Set([
  'sqlmap', 'nikto', 'nmap', 'masscan', 'zgrab', 'wpscan', 'acunetix', 'nessus', 'openvas', 'qualys',
  'burp', 'burpsuite', 'owasp_zap', 'zaproxy', 'arachni', 'skipfish', 'w3af', 'dirbuster', 'dirb',
  'gobuster', 'ffuf', 'feroxbuster', 'wfuzz', 'hydra', 'medusa', 'metasploit', 'msf', 'nuclei', 'httpx',
  'subfinder', 'amass', 'shodan', 'censys', 'whatweb', 'jaeles', 'dalfox', 'xsstrike', 'commix', 'tplmap',
  'fimap', 'uniscan', 'paros', 'webscarab', 'vega', 'grabber', 'havij', 'pangolin', 'absinthe', 'sqlninja',
  'bbscan', 'xray', 'gau', 'gauri', 'waybackurls', 'hakrawler', 'meg', 'netsparker', 'appscan', 'webinspect',
  'securityscan', 'exploit', 'vulnerability', 'zmap', 'nmap_scripting_engine',
]);

const AUTOMATION_UA_IDS = new Set([
  'headlesschrome', 'headless', 'phantomjs', 'playwright', 'puppeteer', 'selenium', 'webdriver', 'scrapy',
  'mechanize', 'httpclient',
]);

const BOT_CLIENT_UA_IDS = new Set([
  'curl', 'wget', 'python_requests', 'python_urllib', 'aiohttp', 'libwww_perl', 'lwp_trivial',
  'go_http_client', 'java_', 'apache_httpclient', 'okhttp', 'axios', 'node_fetch', 'undici',
  'postmanruntime', 'insomnia', 'httpie', 'rest_client', 'winhttp', 'powershell',
]);

const CRAWLER_UA_IDS = new Set([
  'googlebot', 'bingbot', 'baiduspider', 'yandexbot', 'petalbot', 'semrushbot', 'ahrefsbot', 'mj12bot',
  'dotbot', 'bytespider', 'gptbot', 'claudebot', 'ccbot', 'spider', 'crawler', 'scan',
]);

/** @param {{ id?: string } | null} hit */
export function classifyUaHit(hit) {
  if (!hit?.id) return null;
  const id = hit.id;
  if (SCANNER_UA_IDS.has(id) || /\b(scan|exploit|vuln|security)\b/i.test(id)) return 'scanner';
  if (AUTOMATION_UA_IDS.has(id)) return 'automation';
  if (BOT_CLIENT_UA_IDS.has(id)) return 'bot_client';
  if (CRAWLER_UA_IDS.has(id) || /\b(bot|spider|crawler)\b/i.test(id)) return 'crawler';
  return 'suspicious';
}
